In [1]:
import pandas as pd

In [2]:
import numpy as np

In [3]:
dataset=pd.read_csv("Placement.csv")

In [4]:
dataset

,sl_no,gender,ssc_p,ssc_b,hsc_p,hsc_b,hsc_s,degree_p,degree_t,workex,etest_p,specialisation,mba_p,status,salary
0,1,M,67.00,Others,91.00,Others,Commerce,58.00,Sci&Tech,No,55.0,Mkt&HR,58.80,Placed,270000.0
1,2,M,79.33,Central,78.33,Others,Science,77.48,Sci&Tech,Yes,86.5,Mkt&Fin,66.28,Placed,200000.0
2,3,M,65.00,Central,68.00,Central,Arts,64.00,Comm&Mgmt,No,75.0,Mkt&Fin,57.80,Placed,250000.0
3,4,M,56.00,Central,52.00,Central,Science,52.00,Sci&Tech,No,66.0,Mkt&HR,59.43,Not Placed,NaN
4,5,M,85.80,Central,73.60,Central,Commerce,73.30,Comm&Mgmt,No,96.8,Mkt&Fin,55.50,Placed,425000.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
210,211,M,80.60,Others,82.00,Others,Commerce,77.60,Comm&Mgmt,No,91.0,Mkt&Fin,74.49,Placed,400000.0
211,212,M,58.00,Others,60.00,Others,Science,72.00,Sci&Tech,No,74.0,Mkt&Fin,53.62,Placed,275000.0
212,213,M,67.00,Others,67.00,Others,Commerce,73.00,Comm&Mgmt,Yes,59.0,Mkt&Fin,69.72,Placed,295000.0
213,214,F,74.00,Others,66.00,Others,Commerce,58.00,Comm&Mgmt,No,70.0,Mkt&HR,60.23,Placed,204000.0
214,215,M,62.00,Central,58.00,Others,Science,53.00,Comm&Mgmt,No,89.0,Mkt&HR,60.22,Not Placed,NaN

In [5]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 215 entries, 0 to 214
Data columns (total 15 columns):
sl_no             215 non-null int64
gender            215 non-null object
ssc_p             215 non-null float64
ssc_b             215 non-null object
hsc_p             215 non-null float64
hsc_b             215 non-null object
hsc_s             215 non-null object
degree_p          215 non-null float64
degree_t          215 non-null object
workex            215 non-null object
etest_p           215 non-null float64
specialisation    215 non-null object
mba_p             215 non-null float64
status            215 non-null object
salary            148 non-null float64
dtypes: float64(6), int64(1), object(8)
memory usage: 25.3+ KB

**Our output should be** 
Quan-["All quantitative columns"] , Qual=["All qualitative columns"]

In [6]:
dataset.columns

Index(['sl_no', 'gender', 'ssc_p', 'ssc_b', 'hsc_p', 'hsc_b', 'hsc_s',
       'degree_p', 'degree_t', 'workex', 'etest_p', 'specialisation', 'mba_p',
       'status', 'salary'],
      dtype='object')

Now we have to know which datatype belongs to each column names to attain that we have to 
know which functions are supported by this data set  #to know we use dir(dataset)

In [7]:
 dir(dataset)

['T',
 '_AXIS_ALIASES',
 '_AXIS_IALIASES',
 '_AXIS_LEN',
 '_AXIS_NAMES',
 '_AXIS_NUMBERS',
 '_AXIS_ORDERS',
 '_AXIS_REVERSED',
 '__abs__',
 '__add__',
 '__and__',
 '__array__',
 '__array_priority__',
 '__array_wrap__',
 '__bool__',
 '__class__',
 '__contains__',
 '__copy__',
 '__deepcopy__',
 '__delattr__',
 '__delitem__',
 '__dict__',
 '__dir__',
 '__div__',
 '__doc__',
 '__eq__',
 '__finalize__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattr__',
 '__getattribute__',
 '__getitem__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__iand__',
 '__ifloordiv__',
 '__imod__',
 '__imul__',
 '__init__',
 '__init_subclass__',
 '__invert__',
 '__ior__',
 '__ipow__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__ixor__',
 '__le__',
 '__len__',
 '__lt__',
 '__matmul__',
 '__mod__',
 '__module__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__nonzero__',
 '__or__',
 '__pos__',
 '__pow__',
 '__radd__',
 '__rand__',
 '__rdiv__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__rfloordiv__',
 '__rmatmul__',
 '__rmod__',
 '__rmul__',
 '__ror__',
 '__round__',
 '__rpow__',
 '__rsub__',
 '__rtruediv__',
 '__rxor__',
 '__setattr__',
 '__setitem__',
 '__setstate__',
 '__sizeof__',
 '__str__',
 '__sub__',
 '__subclasshook__',
 '__truediv__',
 '__weakref__',
 '__xor__',
 '_accessors',
 '_add_numeric_operations',
 '_add_series_only_operations',
 '_add_series_or_dataframe_operations',
 '_agg_by_level',
 '_agg_examples_doc',
 '_agg_summary_and_see_also_doc',
 '_aggregate',
 '_aggregate_multiple_funcs',
 '_align_frame',
 '_align_series',
 '_box_col_values',
 '_box_item_values',
 '_builtin_table',
 '_check_inplace_setting',
 '_check_is_chained_assignment_possible',
 '_check_label_or_level_ambiguity',
 '_check_percentile',
 '_check_setitem_copy',
 '_clear_item_cache',
 '_clip_with_one_bound',
 '_clip_with_scalar',
 '_combine_const',
 '_combine_frame',
 '_combine_match_columns',
 '_combine_match_index',
 '_consolidate',
 '_consolidate_inplace',
 '_construct_axes_dict',
 '_construct_axes_dict_from',
 '_construct_axes_from_arguments',
 '_constructor',
 '_constructor_expanddim',
 '_constructor_sliced',
 '_convert',
 '_count_level',
 '_create_indexer',
 '_cython_table',
 '_data',
 '_deprecations',
 '_dir_additions',
 '_dir_deletions',
 '_drop_axis',
 '_drop_labels_or_levels',
 '_ensure_valid_index',
 '_find_valid_index',
 '_from_arrays',
 '_from_axes',
 '_get_agg_axis',
 '_get_axis',
 '_get_axis_name',
 '_get_axis_number',
 '_get_axis_resolvers',
 '_get_block_manager_axis',
 '_get_bool_data',
 '_get_cacher',
 '_get_index_resolvers',
 '_get_item_cache',
 '_get_label_or_level_values',
 '_get_numeric_data',
 '_get_space_character_free_column_resolvers',
 '_get_value',
 '_get_values',
 '_getitem_bool_array',
 '_getitem_frame',
 '_getitem_multilevel',
 '_gotitem',
 '_iget_item_cache',
 '_indexed_same',
 '_info_axis',
 '_info_axis_name',
 '_info_axis_number',
 '_info_repr',
 '_init_mgr',
 '_internal_get_values',
 '_internal_names',
 '_internal_names_set',
 '_is_builtin_func',
 '_is_cached',
 '_is_copy',
 '_is_cython_func',
 '_is_datelike_mixed_type',
 '_is_homogeneous_type',
 '_is_label_or_level_reference',
 '_is_label_reference',
 '_is_level_reference',
 '_is_mixed_type',
 '_is_numeric_mixed_type',
 '_is_view',
 '_ix',
 '_ixs',
 '_join_compat',
 '_maybe_cache_changed',
 '_maybe_update_cacher',
 '_metadata',
 '_needs_reindex_multi',
 '_obj_with_exclusions',
 '_protect_consolidate',
 '_reduce',
 '_reindex_axes',
 '_reindex_columns',
 '_reindex_index',
 '_reindex_multi',
 '_reindex_with_indexers',
 '_repr_data_resource_',
 '_repr_fits_horizontal_',
 '_repr_fits_vertical_',
 '_repr_html_',
 '_repr_latex_',
 '_reset_cache',
 '_reset_cacher',
 '_sanitize_column',
 '_selected_obj',
 '_selection',
 '_selection_list',
 '_selection_name',
 '_series',
 '_set_as_cached',
 '_set_axis',
 '_set_axis_name',
 '_set_is_copy',
 '_set_item',
 '_set_value',
 '_setitem_array',
 '_setitem_frame',
 '_setitem_slice',
 '_setup_axes',
 '_shallow_copy',
 '_slice',
 '_stat_axis',
 '_stat_axis_name',
 '_stat_axis_number',
 '_to_dict_of_blocks',
 '_try_aggregate_string_function',
 '_typ',
 '_unpickle_frame_compat',
 '_unpickle_matrix_compat',
 '_update_inplace',
 '_validate_dtype',
 '_values',
 '_where',
 '_xs',
 'abs',
 'add',
 'add_prefix',
 'add_suffix',
 'agg',
 'aggregate',
 'align',
 'all',
 'any',
 'append',
 'apply',
 'applymap',
 'as_matrix',
 'asfreq',
 'asof',
 'assign',
 'astype',
 'at',
 'at_time',
 'axes',
 'between_time',
 'bfill',
 'bool',
 'boxplot',
 'clip',
 'clip_lower',
 'clip_upper',
 'columns',
 'combine',
 'combine_first',
 'compound',
 'copy',
 'corr',
 'corrwith',
 'count',
 'cov',
 'cummax',
 'cummin',
 'cumprod',
 'cumsum',
 'degree_p',
 'degree_t',
 'describe',
 'diff',
 'div',
 'divide',
 'dot',
 'drop',
 'drop_duplicates',
 'droplevel',
 'dropna',
 'dtypes',
 'duplicated',
 'empty',
 'eq',
 'equals',
 'etest_p',
 'eval',
 'ewm',
 'expanding',
 'explode',
 'ffill',
 'fillna',
 'filter',
 'first',
 'first_valid_index',
 'floordiv',
 'from_dict',
 'from_records',
 'ge',
 'gender',
 'get',
 'get_dtype_counts',
 'get_ftype_counts',
 'get_values',
 'groupby',
 'gt',
 'head',
 'hist',
 'hsc_b',
 'hsc_p',
 'hsc_s',
 'iat',
 'idxmax',
 'idxmin',
 'iloc',
 'index',
 'infer_objects',
 'info',
 'insert',
 'interpolate',
 'isin',
 'isna',
 'isnull',
 'items',
 'iteritems',
 'iterrows',
 'itertuples',
 'join',
 'keys',
 'kurt',
 'kurtosis',
 'last',
 'last_valid_index',
 'le',
 'loc',
 'lookup',
 'lt',
 'mad',
 'mask',
 'max',
 'mba_p',
 'mean',
 'median',
 'melt',
 'memory_usage',
 'merge',
 'min',
 'mod',
 'mode',
 'mul',
 'multiply',
 'ndim',
 'ne',
 'nlargest',
 'notna',
 'notnull',
 'nsmallest',
 'nunique',
 'pct_change',
 'pipe',
 'pivot',
 'pivot_table',
 'plot',
 'pop',
 'pow',
 'prod',
 'product',
 'quantile',
 'query',
 'radd',
 'rank',
 'rdiv',
 'reindex',
 'reindex_like',
 'rename',
 'rename_axis',
 'reorder_levels',
 'replace',
 'resample',
 'reset_index',
 'rfloordiv',
 'rmod',
 'rmul',
 'rolling',
 'round',
 'rpow',
 'rsub',
 'rtruediv',
 'salary',
 'sample',
 'select_dtypes',
 'sem',
 'set_axis',
 'set_index',
 'shape',
 'shift',
 'size',
 'skew',
 'sl_no',
 'slice_shift',
 'sort_index',
 'sort_values',
 'sparse',
 'specialisation',
 'squeeze',
 'ssc_b',
 'ssc_p',
 'stack',
 'status',
 'std',
 'style',
 'sub',
 'subtract',
 'sum',
 'swapaxes',
 'swaplevel',
 'tail',
 'take',
 'to_clipboard',
 'to_csv',
 'to_dense',
 'to_dict',
 'to_excel',
 'to_feather',
 'to_gbq',
 'to_hdf',
 'to_html',
 'to_json',
 'to_latex',
 'to_msgpack',
 'to_numpy',
 'to_parquet',
 'to_period',
 'to_pickle',
 'to_records',
 'to_sparse',
 'to_sql',
 'to_stata',
 'to_string',
 'to_timestamp',
 'to_xarray',
 'transform',
 'transpose',
 'truediv',
 'truncate',
 'tshift',
 'tz_convert',
 'tz_localize',
 'unstack',
 'update',
 'values',
 'var',
 'where',
 'workex',
 'xs']

Now we know dtypes function is supported by this dataset

In [8]:
dataset.dtypes

sl_no               int64
gender             object
ssc_p             float64
ssc_b              object
hsc_p             float64
hsc_b              object
hsc_s              object
degree_p          float64
degree_t           object
workex             object
etest_p           float64
specialisation     object
mba_p             float64
status             object
salary            float64
dtype: object

NOw we have what we want only column names with datatypes.
Then check we able to accese one column or not.

In [9]:
genderdata=dataset["gender"].dtypes

In [10]:
genderdata

dtype('O')

In [11]:
#now check one with float 
dataset["hsc_p"].dtypes

dtype('float64')

In [12]:
#Yes! individual column is acceseable 
#now we have to write logic
#let's say If statement
if(genderdata=='O'): #if genter is object print qual
    print("qual")
else:
    print("quan")

qual

The above logic is working but we have to type all column name individually to separate qual and quan.
So, we have to find the way of making it automatic

In [13]:
#so what we usually do to check multiple inputs to one set of procedure we use for loop right?
for column_names in dataset.columns:
    if dataset[column_names].dtypes=="object":
        print("qual")
    else:
        print("quan")

quan
qual
quan
qual
quan
qual
qual
quan
qual
qual
quan
qual
quan
qual
quan

Above code just gave us the column name is quan or qual but we want to know if qual=[column names] same for quan 
how we will attain this?

In [14]:
#first use empty variable to store our values
quan=[]
qual=[]
for column_names in dataset.columns:
    if dataset[column_names].dtypes=="object":
        qual.append(column_names)
        #print("qual")
    else:
        quan.append(column_names)
        #print("quan")

In [15]:
quan

['sl_no', 'ssc_p', 'hsc_p', 'degree_p', 'etest_p', 'mba_p', 'salary']

In [16]:
print ('quan=',quan,'qual=',qual)

quan= ['sl_no', 'ssc_p', 'hsc_p', 'degree_p', 'etest_p', 'mba_p', 'salary'] qual= ['gender', 'ssc_b', 'hsc_b', 'hsc_s', 'degree_t', 'workex', 'specialisation', 'status']

Now this logic works fine so, we have to convert it into class so that we can use it multiple time

In [17]:
def quan_qual():
    quan=[]
    qual=[]
    for column_names in dataset.columns:
        if dataset[column_names].dtypes=="object":
            qual.append(column_names)
            
        else:
            quan.append(column_names)
            
    return quan,qual

In [18]:
quan_qual() #for future use we have to pass dataset into the function

(['sl_no', 'ssc_p', 'hsc_p', 'degree_p', 'etest_p', 'mba_p', 'salary'],
 ['gender',
  'ssc_b',
  'hsc_b',
  'hsc_s',
  'degree_t',
  'workex',
  'specialisation',
  'status'])

In [19]:
def quan_qual(dataset):
    quan=[]
    qual=[]
    for column_names in dataset.columns:
        if dataset[column_names].dtypes=="object":
            qual.append(column_names)
            
        else:
            quan.append(column_names)
            
    return quan,qual

In [20]:
quan_qual(dataset)

(['sl_no', 'ssc_p', 'hsc_p', 'degree_p', 'etest_p', 'mba_p', 'salary'],
 ['gender',
  'ssc_b',
  'hsc_b',
  'hsc_s',
  'degree_t',
  'workex',
  'specialisation',
  'status'])

#Next convert this function into class 
#we saved the class in different .py file and checked it usint different notebook named faircopy

#Now we are going to create mean,median,mode# 
Thump rule is if we work on continu values numerical problem we have to find mean,median,mode.

In [21]:
dataset["ssc_p"].mean()

67.30339534883721

In [22]:
dataset["ssc_p"].median()

67.0

In [23]:
dataset["ssc_p"].mode()[0]

62.0

In [24]:
#Now we know how to find mean,median and mode for seperate colulmn

In [25]:
dataset.describe() #inbuild function to find mean

,sl_no,ssc_p,hsc_p,degree_p,etest_p,mba_p,salary
count,215.000000,215.000000,215.000000,215.000000,215.000000,215.000000,148.000000
mean,108.000000,67.303395,66.333163,66.370186,72.100558,62.278186,288655.405405
std,62.209324,10.827205,10.897509,7.358743,13.275956,5.833385,93457.452420
min,1.000000,40.890000,37.000000,50.000000,50.000000,51.210000,200000.000000
25%,54.500000,60.600000,60.900000,61.000000,60.000000,57.945000,240000.000000
50%,108.000000,67.000000,65.000000,66.000000,71.000000,62.000000,265000.000000
75%,161.500000,75.700000,73.000000,72.000000,83.500000,66.255000,300000.000000
max,215.000000,89.400000,97.700000,91.000000,98.000000,77.890000,940000.000000

The above step we have mean value but not median and mode so, we have to create seperate tabulation with mean,median,and mode.

In [26]:
descriptive=pd.DataFrame()

In [27]:
descriptive #(here, we didn't mention row and column)

Empty DataFrame
Columns: []
Index: []

In [28]:
descriptive=pd.DataFrame(index=["Mean","Median","Mode"],columns=quan)

In [29]:
descriptive

       sl_no ssc_p hsc_p degree_p etest_p mba_p salary
Mean     NaN   NaN   NaN      NaN     NaN   NaN    NaN
Median   NaN   NaN   NaN      NaN     NaN   NaN    NaN
Mode     NaN   NaN   NaN      NaN     NaN   NaN    NaN

In [30]:
descriptive["ssc_p"]["Median"]=0 #now we will see how to acces Value

In [31]:
descriptive

       sl_no ssc_p hsc_p degree_p etest_p mba_p salary
Mean     NaN   NaN   NaN      NaN     NaN   NaN    NaN
Median   NaN     0   NaN      NaN     NaN   NaN    NaN
Mode     NaN   NaN   NaN      NaN     NaN   NaN    NaN

Now we know how to acces one grid in tabulation
now we create all values in tabulation
Lets try to a

In [32]:
descriptive=pd.DataFrame(index=["Mean","Median","Mode"],columns=quan)  #step1: create dataframe with row and column
for column_names in quan:                           #step2:Use for loop for check multiple inputs in one set of procedure
    descriptive[column_names]["Mean"]=dataset[column_names].mean()
    descriptive[column_names]["Median"]=dataset[column_names].median()
    descriptive[column_names]["Mode"]=dataset[column_names].mode()[0]

In [33]:
descriptive

       sl_no    ssc_p    hsc_p degree_p  etest_p    mba_p  salary
Mean     108  67.3034  66.3332  66.3702  72.1006  62.2782  288655
Median   108       67       65       66       71       62  265000
Mode       1       62       63       65       60     56.7  300000

Now we are going to create percentile for 25%,50%,75%,100%

In [34]:
quan #we create percentile only for quan columns

['sl_no', 'ssc_p', 'hsc_p', 'degree_p', 'etest_p', 'mba_p', 'salary']

In [35]:
# First try to find Percentile for one column 
import numpy as np
np.percentile(dataset["ssc_p"],25) #we access one column in dataset and 25 donotes boundry of 25% of data

60.599999999999994

Now what we get 25th percentile that means our 25% of data exist between intial value to 25th value (60.599).
And other words minimum value of collumn ssc_p lower value and highest value of 25% of data is 60.599

In [36]:
#Instead of find all columns value one by one we can creat it as dataframe 
descriptive=pd.DataFrame(index=["Mean","Median","Mode","Q1:25%","Q2:50%","Q3:75%","99%","Q4:100%"],columns=quan)  
for column_names in quan:                           
    descriptive[column_names]["Mean"]=dataset[column_names].mean()
    descriptive[column_names]["Median"]=dataset[column_names].median()
    descriptive[column_names]["Mode"]=dataset[column_names].mode()[0]
    #Before start we should create columns and rows to save value right?
    descriptive[column_names]["Q1:25%"]=dataset.describe()[column_names]["25%"]
    descriptive[column_names]["Q2:50%"]=dataset.describe()[column_names]["50%"]
    descriptive[column_names]["Q3:75%"]=dataset.describe()[column_names]["75%"]
    descriptive[column_names]["99%"]   =np.percentile(dataset[column_names],99)
    descriptive[column_names]["Q4:100%"]=dataset.describe()[column_names]["max"]

NOTE: dataset.describe() is a Pandas method, 
    and it automatically skips NaN values.
    np.percentile() is a NumPy function,
    and it does not automatically ignore NaN values. That's why we use this for work flow later we will change it

In [37]:
descriptive

          sl_no    ssc_p    hsc_p degree_p  etest_p    mba_p  salary
Mean        108  67.3034  66.3332  66.3702  72.1006  62.2782  288655
Median      108       67       65       66       71       62  265000
Mode          1       62       63       65       60     56.7  300000
Q1:25%     54.5     60.6     60.9       61       60   57.945  240000
Q2:50%      108       67       65       66       71       62  265000
Q3:75%    161.5     75.7       73       72     83.5   66.255  300000
99%      212.86       87    91.86    83.86       97  76.1142     NaN
Q4:100%     215     89.4     97.7       91       98    77.89  940000

##Now we are going to find IQR value to detect presence of lesser_outlier and greater_outlier
so we have to add IQR value,1.5rule,perimited_lesser value, perimited_greater value of dataset,minimum of dataset,maximum of dataset to the dataframe.

In [38]:
#Instead of find all columns value one by one we can creat it as dataframe 
descriptive=pd.DataFrame(index=["Mean","Median","Mode","Q1:25%","Q2:50%","Q3:75%","99%","Q4:100%","IQR","1.5rule",
                                "lesser_per","greater_per","Mini","Max"],columns=quan)  
for column_names in quan:                           
    descriptive[column_names]["Mean"]=dataset[column_names].mean()
    descriptive[column_names]["Median"]=dataset[column_names].median()
    descriptive[column_names]["Mode"]=dataset[column_names].mode()[0]
    #Before start we should create columns and rows to save value right?
    descriptive[column_names]["Q1:25%"]=dataset.describe()[column_names]["25%"]
    descriptive[column_names]["Q2:50%"]=dataset.describe()[column_names]["50%"]
    descriptive[column_names]["Q3:75%"]=dataset.describe()[column_names]["75%"]
    descriptive[column_names]["99%"]   =np.percentile(dataset[column_names],99)
    descriptive[column_names]["Q4:100%"]=dataset.describe()[column_names]["max"]
    #so,now we are going to add IQR values to fing outliers. Add column and row to the dataframe.

In [39]:
descriptive

              sl_no    ssc_p    hsc_p degree_p  etest_p    mba_p  salary
Mean            108  67.3034  66.3332  66.3702  72.1006  62.2782  288655
Median          108       67       65       66       71       62  265000
Mode              1       62       63       65       60     56.7  300000
Q1:25%         54.5     60.6     60.9       61       60   57.945  240000
Q2:50%          108       67       65       66       71       62  265000
Q3:75%        161.5     75.7       73       72     83.5   66.255  300000
99%          212.86       87    91.86    83.86       97  76.1142     NaN
Q4:100%         215     89.4     97.7       91       98    77.89  940000
IQR             NaN      NaN      NaN      NaN      NaN      NaN     NaN
1.5rule         NaN      NaN      NaN      NaN      NaN      NaN     NaN
lesser_per      NaN      NaN      NaN      NaN      NaN      NaN     NaN
greater_per     NaN      NaN      NaN      NaN      NaN      NaN     NaN
Mini            NaN      NaN      NaN      NaN      NaN      NaN     NaN
Max             NaN      NaN      NaN      NaN      NaN      NaN     NaN

#to find IQR 
IQR=Q3-Q1
lesser_pre=Q1-1.5*(IQR)
greater_pre=Q3+1.5*(IQR)

In [40]:
descriptive=pd.DataFrame(index=["Mean","Median","Mode","Q1:25%","Q2:50%","Q3:75%","99%","Q4:100%","IQR","1.5rule",
                                "lesser_per","greater_per","Mini","Max"],columns=quan)  
for column_names in quan:                           
    descriptive[column_names]["Mean"]=dataset[column_names].mean()
    descriptive[column_names]["Median"]=dataset[column_names].median()
    descriptive[column_names]["Mode"]=dataset[column_names].mode()[0]
    #Before start we should create columns and rows to save value right?
    descriptive[column_names]["Q1:25%"]=dataset.describe()[column_names]["25%"]
    descriptive[column_names]["Q2:50%"]=dataset.describe()[column_names]["50%"]
    descriptive[column_names]["Q3:75%"]=dataset.describe()[column_names]["75%"]
    descriptive[column_names]["99%"]   =np.percentile(dataset[column_names],99)
    descriptive[column_names]["Q4:100%"]=dataset.describe()[column_names]["max"]
    #so,now we are going to add IQR values to fing outliers. Add column and row to the dataframe.
    descriptive[column_names]["IQR"]=descriptive[column_names]["Q3:75%"]-descriptive[column_names]["Q1:25%"]
    descriptive[column_names]["1.5rule"]=1.5*descriptive[column_names]["IQR"]
    descriptive[column_names]["lesser_per"]=descriptive[column_names]["Q1:25%"]-descriptive[column_names]["1.5rule"]
    descriptive[column_names]["greater_per"]=descriptive[column_names]["Q3:75%"]+descriptive[column_names]["1.5rule"]
    descriptive[column_names]["Mini"]=dataset[column_names].min()
    descriptive[column_names]["Max"]=dataset[column_names].max()

In [41]:
descriptive

              sl_no    ssc_p    hsc_p degree_p  etest_p    mba_p  salary
Mean            108  67.3034  66.3332  66.3702  72.1006  62.2782  288655
Median          108       67       65       66       71       62  265000
Mode              1       62       63       65       60     56.7  300000
Q1:25%         54.5     60.6     60.9       61       60   57.945  240000
Q2:50%          108       67       65       66       71       62  265000
Q3:75%        161.5     75.7       73       72     83.5   66.255  300000
99%          212.86       87    91.86    83.86       97  76.1142     NaN
Q4:100%         215     89.4     97.7       91       98    77.89  940000
IQR             107     15.1     12.1       11     23.5     8.31   60000
1.5rule       160.5    22.65    18.15     16.5    35.25   12.465   90000
lesser_per     -106    37.95    42.75     44.5    24.75    45.48  150000
greater_per     322    98.35    91.15     88.5   118.75    78.72  390000
Mini              1    40.89       37       50       50    51.21  200000
Max             215     89.4     97.7       91       98    77.89  940000

#Now we have all values in our dataset
#Now compare permited lesser value and minimum value to detect lesser outliers. same for greater outliers.

#How to find lesser ourlier and greater ourlier 
#lesser_outlier=Mini<lesser_per if this condition true there is outlier 
#greater_outlier= max>greater_per if this condition true thire is outlier.

In [42]:
#lets try for one column 
descriptive["hsc_p"]["Mini"]<descriptive["hsc_p"]["lesser_per"] #see this condition is true now we able to write code

True

In [43]:
print(descriptive["hsc_p"]["lesser_per"])

42.75

In [44]:
#so we can use if condition to find outliers  and save all columns names if it has outliers.
#use empty list to save variables 
lesser_de=[]
greater_de=[]
for column_names in quan:
    if(descriptive[column_names]["Mini"]<descriptive[column_names]["lesser_per"]):
        lesser_de.append(column_names)
    #here we don't use else or elif because if the above condition is true else or elife conditions won't work
    if(descriptive[column_names]["Max"]>descriptive[column_names]["greater_per"]):
        greater_de.append(column_names)

In [45]:
lesser_de

['hsc_p']

In [46]:
greater_de

['hsc_p', 'degree_p', 'salary']

#Now we got which column have lesser and greater outliers.

In [47]:
#Now we should replace the outlier columns by lesser_per and greater_per.
#How we replace one cell commonly?

In [48]:
#step:1 access the cell[condition] = new value of the cell right? 
for column_names in lesser_de:
    dataset[column_names][dataset[column_names]<descriptive[column_names]["lesser_per"]]=descriptive[column_names]["lesser_per"]
#location- dataset[column_names]
#condition [dataset[column_names]<descriptive[column_names]["lesser_per"]]
#Note: we can't use only column_names as veriable because what in that only lable(hsc_p) not value.
#If above condition is true replace this value : descriptive[column_names]["lesser_per"]

#step:2 same proceduce for greater_de just change as fit as for greater.
for column_names in greater_de:
    dataset[column_names][dataset[column_names]>descriptive[column_names]["greater_per"]]=descriptive[column_names]["greater_per"]

C:\Anaconda3\envs\aiml\lib\site-packages\ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  This is separate from the ipykernel package so we can avoid doing imports until
C:\Anaconda3\envs\aiml\lib\site-packages\ipykernel_launcher.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  # This is added back by InteractiveShellApp.init_path()

In [49]:
descriptive

              sl_no    ssc_p    hsc_p degree_p  etest_p    mba_p  salary
Mean            108  67.3034  66.3332  66.3702  72.1006  62.2782  288655
Median          108       67       65       66       71       62  265000
Mode              1       62       63       65       60     56.7  300000
Q1:25%         54.5     60.6     60.9       61       60   57.945  240000
Q2:50%          108       67       65       66       71       62  265000
Q3:75%        161.5     75.7       73       72     83.5   66.255  300000
99%          212.86       87    91.86    83.86       97  76.1142     NaN
Q4:100%         215     89.4     97.7       91       98    77.89  940000
IQR             107     15.1     12.1       11     23.5     8.31   60000
1.5rule       160.5    22.65    18.15     16.5    35.25   12.465   90000
lesser_per     -106    37.95    42.75     44.5    24.75    45.48  150000
greater_per     322    98.35    91.15     88.5   118.75    78.72  390000
Mini              1    40.89       37       50       50    51.21  200000
Max             215     89.4     97.7       91       98    77.89  940000

In [50]:
descriptive=pd.DataFrame(index=["Mean","Median","Mode","Q1:25%","Q2:50%","Q3:75%","99%","Q4:100%","IQR","1.5rule",
                                "lesser_per","greater_per","Mini","Max"],columns=quan)  
for column_names in quan:                           
    descriptive[column_names]["Mean"]=dataset[column_names].mean()
    descriptive[column_names]["Median"]=dataset[column_names].median()
    descriptive[column_names]["Mode"]=dataset[column_names].mode()[0]
    #Before start we should create columns and rows to save value right?
    descriptive[column_names]["Q1:25%"]=dataset.describe()[column_names]["25%"]
    descriptive[column_names]["Q2:50%"]=dataset.describe()[column_names]["50%"]
    descriptive[column_names]["Q3:75%"]=dataset.describe()[column_names]["75%"]
    descriptive[column_names]["99%"]   =np.percentile(dataset[column_names],99)
    descriptive[column_names]["Q4:100%"]=dataset.describe()[column_names]["max"]
    #so,now we are going to add IQR values to fing outliers. Add column and row to the dataframe.
    descriptive[column_names]["IQR"]=descriptive[column_names]["Q3:75%"]-descriptive[column_names]["Q1:25%"]
    descriptive[column_names]["1.5rule"]=1.5*descriptive[column_names]["IQR"]
    descriptive[column_names]["lesser_per"]=descriptive[column_names]["Q1:25%"]-descriptive[column_names]["1.5rule"]
    descriptive[column_names]["greater_per"]=descriptive[column_names]["Q3:75%"]+descriptive[column_names]["1.5rule"]
    descriptive[column_names]["Mini"]=dataset[column_names].min()
    descriptive[column_names]["Max"]=dataset[column_names].max()

In [51]:
descriptive

              sl_no    ssc_p    hsc_p degree_p  etest_p    mba_p  salary
Mean            108  67.3034  66.3347  66.3586  72.1006  62.2782  277649
Median          108       67       65       66       71       62  265000
Mode              1       62       63       65       60     56.7  300000
Q1:25%         54.5     60.6     60.9       61       60   57.945  240000
Q2:50%          108       67       65       66       71       62  265000
Q3:75%        161.5     75.7       73       72     83.5   66.255  300000
99%          212.86       87   91.129    83.86       97  76.1142     NaN
Q4:100%         215     89.4    91.15     88.5       98    77.89  390000
IQR             107     15.1     12.1       11     23.5     8.31   60000
1.5rule       160.5    22.65    18.15     16.5    35.25   12.465   90000
lesser_per     -106    37.95    42.75     44.5    24.75    45.48  150000
greater_per     322    98.35    91.15     88.5   118.75    78.72  390000
Mini              1    40.89    42.75       50       50    51.21  200000
Max             215     89.4    91.15     88.5       98    77.89  390000

In [52]:
#Now check this condition if the empty variable remains empth our logic is write
lesser_de=[]
greater_de=[]
for column_names in quan:
    if(descriptive[column_names]["Mini"]<descriptive[column_names]["lesser_per"]):
        lesser_de.append(column_names)
    #here we don't use else or elif because if the above condition is true else or elife conditions won't work
    if(descriptive[column_names]["Max"]>descriptive[column_names]["greater_per"]):
        greater_de.append(column_names)

In [53]:
lesser_de=[]

In [54]:
greater_de=[]

#Our logic is correct.

#our next topic is frequency(repetation of each and every number in column)

In [55]:
#To find frequency we have inbuild function 
dataset["hsc_p"].value_counts() #here first column is index and next one is values. 
#we can access this index and values alone too

63.00    14
62.00    12
67.00     9
60.00     9
64.00     8
         ..
60.80     1
89.83     1
66.60     1
87.60     1
91.00     1
Name: hsc_p, Length: 91, dtype: int64

#Task:
#Now we have to find frequency,relative_frequency and cumsum for all our quan columns. 
#we can't create Frequency_Table like descriptive for our requirement because frequency
#gives value for each and every entry in the each column.

In [56]:
#create new dataframe for frequency table
frequency_Tab=pd.DataFrame(columns=["Unique_values","Frequency","Relative_Frequency","cumsum"])

In [57]:
frequency_Tab

Empty DataFrame
Columns: [Unique_values, Frequency, Relative_Frequency, cumsum]
Index: []

In [58]:
#now we are going to assing values for all columns.
#frequency_Tab["Unique_values"]=dataset["ssc_p"].value_counts().index #(In this step we assing Unique_values)

In [59]:
frequency_Tab

Empty DataFrame
Columns: [Unique_values, Frequency, Relative_Frequency, cumsum]
Index: []

In [60]:
frequency_Tab["Unique_values"]=dataset["ssc_p"].value_counts().index
frequency_Tab["Frequency"]=dataset["ssc_p"].value_counts().values
#next relative_frequency= Frequency/Total no of frequency

In [61]:
#Total number of values in frequency column 
Tno_values=frequency_Tab["Frequency"].sum()

In [62]:
Tno_values

215

In [63]:
#Next we have to assign values for relative_frequency and cumsum
frequency_Tab["Relative_Frequency"]=frequency_Tab["Frequency"]/frequency_Tab["Frequency"].sum()
frequency_Tab["cumsum"]=frequency_Tab["Relative_Frequency"].cumsum()

In [64]:
frequency_Tab

     Unique_values  Frequency  Relative_Frequency    cumsum
0            62.00         11            0.051163  0.051163
1            63.00         10            0.046512  0.097674
2            67.00          9            0.041860  0.139535
3            52.00          9            0.041860  0.181395
4            73.00          9            0.041860  0.223256
..             ...        ...                 ...       ...
98           80.60          1            0.004651  0.981395
99           65.20          1            0.004651  0.986047
100          80.40          1            0.004651  0.990698
101          59.96          1            0.004651  0.995349
102          78.50          1            0.004651  1.000000

[103 rows x 4 columns]

Now we have all frequency values for quan column"ssc_p". 
Then we have to find frequency for rest of columns.
What we usually do if we find parten and that's suitable for everything? yes next, we are going to convert our checked logics
In to function and class so, that we can reuse it.

In [65]:
def freq_Tab(dataset,column_names):
    frequency_Tab=pd.DataFrame(columns=["Unique_values","Frequency","Relative_Frequency","cumsum"])
    frequency_Tab["Unique_values"]=dataset[column_names].value_counts().index
    frequency_Tab["Frequency"]=dataset[column_names].value_counts().values
    frequency_Tab["Relative_Frequency"]=frequency_Tab["Frequency"]/frequency_Tab["Frequency"].sum()
    frequency_Tab["cumsum"]=frequency_Tab["Relative_Frequency"].cumsum()
    return frequency_Tab

In [66]:
column_names

'salary'

In [67]:
"hsc_p"

'hsc_p'

In [68]:
freq_Tab(dataset,"hsc_p")

    Unique_values  Frequency  Relative_Frequency    cumsum
0           63.00         14            0.065116  0.065116
1           62.00         12            0.055814  0.120930
2           67.00          9            0.041860  0.162791
3           60.00          9            0.041860  0.204651
4           64.00          8            0.037209  0.241860
..            ...        ...                 ...       ...
86          60.80          1            0.004651  0.981395
87          89.83          1            0.004651  0.986047
88          66.60          1            0.004651  0.990698
89          87.60          1            0.004651  0.995349
90          91.00          1            0.004651  1.000000

[91 rows x 4 columns]

In [69]:
quan

['sl_no', 'ssc_p', 'hsc_p', 'degree_p', 'etest_p', 'mba_p', 'salary']

In [70]:
descriptive

              sl_no    ssc_p    hsc_p degree_p  etest_p    mba_p  salary
Mean            108  67.3034  66.3347  66.3586  72.1006  62.2782  277649
Median          108       67       65       66       71       62  265000
Mode              1       62       63       65       60     56.7  300000
Q1:25%         54.5     60.6     60.9       61       60   57.945  240000
Q2:50%          108       67       65       66       71       62  265000
Q3:75%        161.5     75.7       73       72     83.5   66.255  300000
99%          212.86       87   91.129    83.86       97  76.1142     NaN
Q4:100%         215     89.4    91.15     88.5       98    77.89  390000
IQR             107     15.1     12.1       11     23.5     8.31   60000
1.5rule       160.5    22.65    18.15     16.5    35.25   12.465   90000
lesser_per     -106    37.95    42.75     44.5    24.75    45.48  150000
greater_per     322    98.35    91.15     88.5   118.75    78.72  390000
Mini              1    40.89    42.75       50       50    51.21  200000
Max             215     89.4    91.15     88.5       98    77.89  390000

In [71]:
def detect_lesser_greater(quan,column_names):
    lesser_de=[]
    greater_de=[]
    for column_names in quan:
        if(descriptive[column_names]["Mini"]<descriptive[column_names]["lesser_per"]):
            lesser_de.append(column_names)
        #here we don't use else or elif because if the above condition is true else or elife conditions won't work
        if(descriptive[column_names]["Max"]>descriptive[column_names]["greater_per"]):
            greater_de.append(column_names)
    return lesser_de,greater_de

In [72]:
detect_lesser_greater(quan,"hsc_P")

([], [])

In [73]:
def descriptive_Tab(dataset,quan):
    descriptive=pd.DataFrame(index=["Mean","Median","Mode","Q1:25%","Q2:50%","Q3:75%","99%","Q4:100%","IQR","1.5rule",
                                "lesser_per","greater_per","Mini","Max"],columns=quan)  
    for column_names in quan:                           
        descriptive[column_names]["Mean"]=dataset[column_names].mean()
        descriptive[column_names]["Median"]=dataset[column_names].median()
        descriptive[column_names]["Mode"]=dataset[column_names].mode()[0]
        #Before start we should create columns and rows to save value right?
        descriptive[column_names]["Q1:25%"]=dataset.describe()[column_names]["25%"]
        descriptive[column_names]["Q2:50%"]=dataset.describe()[column_names]["50%"]
        descriptive[column_names]["Q3:75%"]=dataset.describe()[column_names]["75%"]
        descriptive[column_names]["99%"]   =np.percentile(dataset[column_names],99)
        descriptive[column_names]["Q4:100%"]=dataset.describe()[column_names]["max"]
        #so,now we are going to add IQR values to fing outliers. Add column and row to the dataframe.
        descriptive[column_names]["IQR"]=descriptive[column_names]["Q3:75%"]-descriptive[column_names]["Q1:25%"]
        descriptive[column_names]["1.5rule"]=1.5*descriptive[column_names]["IQR"]
        descriptive[column_names]["lesser_per"]=descriptive[column_names]["Q1:25%"]-descriptive[column_names]["1.5rule"]
        descriptive[column_names]["greater_per"]=descriptive[column_names]["Q3:75%"]+descriptive[column_names]["1.5rule"]
        descriptive[column_names]["Mini"]=dataset[column_names].min()
        descriptive[column_names]["Max"]=dataset[column_names].max()
    return descriptive #while convert logic into function position of return statement is important

In [74]:
descriptive_Tab(dataset,quan)

              sl_no    ssc_p    hsc_p degree_p  etest_p    mba_p  salary
Mean            108  67.3034  66.3347  66.3586  72.1006  62.2782  277649
Median          108       67       65       66       71       62  265000
Mode              1       62       63       65       60     56.7  300000
Q1:25%         54.5     60.6     60.9       61       60   57.945  240000
Q2:50%          108       67       65       66       71       62  265000
Q3:75%        161.5     75.7       73       72     83.5   66.255  300000
99%          212.86       87   91.129    83.86       97  76.1142     NaN
Q4:100%         215     89.4    91.15     88.5       98    77.89  390000
IQR             107     15.1     12.1       11     23.5     8.31   60000
1.5rule       160.5    22.65    18.15     16.5    35.25   12.465   90000
lesser_per     -106    37.95    42.75     44.5    24.75    45.48  150000
greater_per     322    98.35    91.15     88.5   118.75    78.72  390000
Mini              1    40.89    42.75       50       50    51.21  200000
Max             215     89.4    91.15     88.5       98    77.89  390000

In [75]:
lesser_de

[]

In [76]:
def Replace_outliers(dataset,lesser_de,greater_de,descriptive):
    for column_names in lesser_de:
        dataset[column_names][dataset[column_names]<descriptive[column_names]["lesser_per"]]=descriptive[column_names]
        ["lesser_per"]
    for column_names in greater_de:
        dataset[column_names][dataset[column_names]>descriptive[column_names]["greater_per"]]=descriptive[column_names]
        ["greater_per"]
    return descriptive

##Histogram,skewness,kurtosis.

##Now we are going to find skewness,kurtosis for all columns in quan one by one.
Then,we have to odd this values into our descriptive dataframe.

In [77]:
# Ok let's see how to find skewness. To find skewness and kurtosis we have to know which funtion names works for this column.
dir(dataset["ssc_p"])

['T',
 '_AXIS_ALIASES',
 '_AXIS_IALIASES',
 '_AXIS_LEN',
 '_AXIS_NAMES',
 '_AXIS_NUMBERS',
 '_AXIS_ORDERS',
 '_AXIS_REVERSED',
 '_HANDLED_TYPES',
 '__abs__',
 '__add__',
 '__and__',
 '__array__',
 '__array_priority__',
 '__array_ufunc__',
 '__array_wrap__',
 '__bool__',
 '__class__',
 '__contains__',
 '__copy__',
 '__deepcopy__',
 '__delattr__',
 '__delitem__',
 '__dict__',
 '__dir__',
 '__div__',
 '__divmod__',
 '__doc__',
 '__eq__',
 '__finalize__',
 '__float__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattr__',
 '__getattribute__',
 '__getitem__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__iand__',
 '__ifloordiv__',
 '__imod__',
 '__imul__',
 '__init__',
 '__init_subclass__',
 '__int__',
 '__invert__',
 '__ior__',
 '__ipow__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__ixor__',
 '__le__',
 '__len__',
 '__long__',
 '__lt__',
 '__matmul__',
 '__mod__',
 '__module__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__nonzero__',
 '__or__',
 '__pos__',
 '__pow__',
 '__radd__',
 '__rand__',
 '__rdiv__',
 '__rdivmod__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__rfloordiv__',
 '__rmatmul__',
 '__rmod__',
 '__rmul__',
 '__ror__',
 '__round__',
 '__rpow__',
 '__rsub__',
 '__rtruediv__',
 '__rxor__',
 '__setattr__',
 '__setitem__',
 '__setstate__',
 '__sizeof__',
 '__str__',
 '__sub__',
 '__subclasshook__',
 '__truediv__',
 '__weakref__',
 '__xor__',
 '_accessors',
 '_add_numeric_operations',
 '_add_series_only_operations',
 '_add_series_or_dataframe_operations',
 '_agg_by_level',
 '_agg_examples_doc',
 '_agg_see_also_doc',
 '_aggregate',
 '_aggregate_multiple_funcs',
 '_align_frame',
 '_align_series',
 '_binop',
 '_box_item_values',
 '_builtin_table',
 '_can_hold_na',
 '_check_inplace_setting',
 '_check_is_chained_assignment_possible',
 '_check_label_or_level_ambiguity',
 '_check_percentile',
 '_check_setitem_copy',
 '_clear_item_cache',
 '_clip_with_one_bound',
 '_clip_with_scalar',
 '_consolidate',
 '_consolidate_inplace',
 '_construct_axes_dict',
 '_construct_axes_dict_from',
 '_construct_axes_from_arguments',
 '_constructor',
 '_constructor_expanddim',
 '_constructor_sliced',
 '_convert',
 '_create_indexer',
 '_cython_table',
 '_data',
 '_deprecations',
 '_dir_additions',
 '_dir_deletions',
 '_drop_axis',
 '_drop_labels_or_levels',
 '_find_valid_index',
 '_formatting_values',
 '_from_axes',
 '_get_axis',
 '_get_axis_name',
 '_get_axis_number',
 '_get_axis_resolvers',
 '_get_block_manager_axis',
 '_get_bool_data',
 '_get_cacher',
 '_get_index_resolvers',
 '_get_item_cache',
 '_get_label_or_level_values',
 '_get_numeric_data',
 '_get_space_character_free_column_resolvers',
 '_get_value',
 '_get_values',
 '_get_values_tuple',
 '_get_with',
 '_gotitem',
 '_iget_item_cache',
 '_index',
 '_indexed_same',
 '_info_axis',
 '_info_axis_name',
 '_info_axis_number',
 '_init_dict',
 '_init_mgr',
 '_internal_get_values',
 '_internal_names',
 '_internal_names_set',
 '_is_builtin_func',
 '_is_cached',
 '_is_copy',
 '_is_cython_func',
 '_is_datelike_mixed_type',
 '_is_homogeneous_type',
 '_is_label_or_level_reference',
 '_is_label_reference',
 '_is_level_reference',
 '_is_mixed_type',
 '_is_numeric_mixed_type',
 '_is_view',
 '_ix',
 '_ixs',
 '_map_values',
 '_maybe_cache_changed',
 '_maybe_update_cacher',
 '_metadata',
 '_ndarray_values',
 '_needs_reindex_multi',
 '_obj_with_exclusions',
 '_protect_consolidate',
 '_reduce',
 '_reindex_axes',
 '_reindex_indexer',
 '_reindex_multi',
 '_reindex_with_indexers',
 '_repr_data_resource_',
 '_repr_latex_',
 '_reset_cache',
 '_reset_cacher',
 '_selected_obj',
 '_selection',
 '_selection_list',
 '_selection_name',
 '_set_as_cached',
 '_set_axis',
 '_set_axis_name',
 '_set_is_copy',
 '_set_item',
 '_set_labels',
 '_set_name',
 '_set_subtyp',
 '_set_value',
 '_set_values',
 '_set_with',
 '_set_with_engine',
 '_setup_axes',
 '_shallow_copy',
 '_slice',
 '_stat_axis',
 '_stat_axis_name',
 '_stat_axis_number',
 '_to_dict_of_blocks',
 '_try_aggregate_string_function',
 '_typ',
 '_unpickle_series_compat',
 '_update_inplace',
 '_validate_dtype',
 '_values',
 '_where',
 '_xs',
 'abs',
 'add',
 'add_prefix',
 'add_suffix',
 'agg',
 'aggregate',
 'align',
 'all',
 'any',
 'append',
 'apply',
 'argmax',
 'argmin',
 'argsort',
 'array',
 'as_matrix',
 'asfreq',
 'asof',
 'astype',
 'at',
 'at_time',
 'autocorr',
 'axes',
 'between',
 'between_time',
 'bfill',
 'bool',
 'clip',
 'clip_lower',
 'clip_upper',
 'combine',
 'combine_first',
 'compound',
 'compress',
 'copy',
 'corr',
 'count',
 'cov',
 'cummax',
 'cummin',
 'cumprod',
 'cumsum',
 'describe',
 'diff',
 'div',
 'divide',
 'divmod',
 'dot',
 'drop',
 'drop_duplicates',
 'droplevel',
 'dropna',
 'dtype',
 'dtypes',
 'duplicated',
 'empty',
 'eq',
 'equals',
 'ewm',
 'expanding',
 'explode',
 'factorize',
 'ffill',
 'fillna',
 'filter',
 'first',
 'first_valid_index',
 'floordiv',
 'from_array',
 'ge',
 'get',
 'get_dtype_counts',
 'get_ftype_counts',
 'get_values',
 'groupby',
 'gt',
 'hasnans',
 'head',
 'hist',
 'iat',
 'idxmax',
 'idxmin',
 'iloc',
 'index',
 'infer_objects',
 'interpolate',
 'is_monotonic',
 'is_monotonic_decreasing',
 'is_monotonic_increasing',
 'is_unique',
 'isin',
 'isna',
 'isnull',
 'item',
 'items',
 'iteritems',
 'keys',
 'kurt',
 'kurtosis',
 'last',
 'last_valid_index',
 'le',
 'loc',
 'lt',
 'mad',
 'map',
 'mask',
 'max',
 'mean',
 'median',
 'memory_usage',
 'min',
 'mod',
 'mode',
 'mul',
 'multiply',
 'name',
 'nbytes',
 'ndim',
 'ne',
 'nlargest',
 'nonzero',
 'notna',
 'notnull',
 'nsmallest',
 'nunique',
 'pct_change',
 'pipe',
 'plot',
 'pop',
 'pow',
 'prod',
 'product',
 'ptp',
 'put',
 'quantile',
 'radd',
 'rank',
 'ravel',
 'rdiv',
 'rdivmod',
 'reindex',
 'reindex_like',
 'rename',
 'rename_axis',
 'reorder_levels',
 'repeat',
 'replace',
 'resample',
 'reset_index',
 'rfloordiv',
 'rmod',
 'rmul',
 'rolling',
 'round',
 'rpow',
 'rsub',
 'rtruediv',
 'sample',
 'searchsorted',
 'sem',
 'set_axis',
 'shape',
 'shift',
 'size',
 'skew',
 'slice_shift',
 'sort_index',
 'sort_values',
 'squeeze',
 'std',
 'sub',
 'subtract',
 'sum',
 'swapaxes',
 'swaplevel',
 'tail',
 'take',
 'to_clipboard',
 'to_csv',
 'to_dense',
 'to_dict',
 'to_excel',
 'to_frame',
 'to_hdf',
 'to_json',
 'to_latex',
 'to_list',
 'to_msgpack',
 'to_numpy',
 'to_period',
 'to_pickle',
 'to_sparse',
 'to_sql',
 'to_string',
 'to_timestamp',
 'to_xarray',
 'transform',
 'transpose',
 'truediv',
 'truncate',
 'tshift',
 'tz_convert',
 'tz_localize',
 'unique',
 'unstack',
 'update',
 'value_counts',
 'values',
 'var',
 'view',
 'where',
 'xs']

In [78]:
#we know skew for "skewness" and kurtosis for "kurtosis". now let's try for one column.
print(dataset["ssc_p"].skew())
dataset["ssc_p"].kurtosis()

-0.13264949031456927

-0.6075102066986688

In [79]:
#If skewness (-0.1326<0) It's a negative skewness so we assume that mean>median>mode.
summary_Tab=pd.DataFrame(index=["Mean","Median","Mode","skew","kurtosis"],columns=quan)  
for column_names in quan:
    summary_Tab[column_names]["Mean"]=dataset[column_names].mean()
    summary_Tab[column_names]["Median"]=dataset[column_names].median()
    summary_Tab[column_names]["Mode"]=dataset[column_names].mode()[0]
    summary_Tab[column_names]["skew"]=dataset[column_names].skew()
    summary_Tab[column_names]["kurtosis"]=dataset[column_names].kurtosis()

In [80]:
summary_Tab

         sl_no     ssc_p      hsc_p   degree_p   etest_p     mba_p    salary
Mean       108   67.3034    66.3347    66.3586   72.1006   62.2782    277649
Median     108        67         65         66        71        62    265000
Mode         1        62         63         65        60      56.7    300000
skew         0 -0.132649   0.162611   0.204164  0.282308  0.313576    0.8067
kurtosis  -1.2  -0.60751  0.0869008 -0.0974897  -1.08858 -0.470723 -0.239837

Now we have to create table for all columns and rows for feature use

In [81]:
def descriptive_Tab(dataset,quan):
    descriptive=pd.DataFrame(index=["Mean","Median","Mode","Q1:25%","Q2:50%","Q3:75%","99%","Q4:100%","IQR","1.5rule",
                                "lesser_per","greater_per","Mini","Max","skew","kurtosis"],columns=quan)  
    for column_names in quan:                           
        descriptive[column_names]["Mean"]=dataset[column_names].mean()
        descriptive[column_names]["Median"]=dataset[column_names].median()
        descriptive[column_names]["Mode"]=dataset[column_names].mode()[0]
        #Before start we should create columns and rows to save value right?
        descriptive[column_names]["Q1:25%"]=dataset.describe()[column_names]["25%"]
        descriptive[column_names]["Q2:50%"]=dataset.describe()[column_names]["50%"]
        descriptive[column_names]["Q3:75%"]=dataset.describe()[column_names]["75%"]
        descriptive[column_names]["99%"]   =np.percentile(dataset[column_names],99)
        descriptive[column_names]["Q4:100%"]=dataset.describe()[column_names]["max"]
        #so,now we are going to add IQR values to fing outliers. Add column and row to the dataframe.
        descriptive[column_names]["IQR"]=descriptive[column_names]["Q3:75%"]-descriptive[column_names]["Q1:25%"]
        descriptive[column_names]["1.5rule"]=1.5*descriptive[column_names]["IQR"]
        descriptive[column_names]["lesser_per"]=descriptive[column_names]["Q1:25%"]-descriptive[column_names]["1.5rule"]
        descriptive[column_names]["greater_per"]=descriptive[column_names]["Q3:75%"]+descriptive[column_names]["1.5rule"]
        descriptive[column_names]["Mini"]=dataset[column_names].min()
        descriptive[column_names]["Max"]=dataset[column_names].max()
        descriptive[column_names]["skew"]=dataset[column_names].skew()
        descriptive[column_names]["kurtosis"]=dataset[column_names].kurtosis()
    return descriptive

In [82]:
descriptive_Tab(dataset,quan)

,sl_no,ssc_p,hsc_p,degree_p,etest_p,mba_p,salary
Mean,108,67.3034,66.3347,66.3586,72.1006,62.2782,277649
Median,108,67,65,66,71,62,265000
Mode,1,62,63,65,60,56.7,300000
Q1:25%,54.5,60.6,60.9,61,60,57.945,240000
Q2:50%,108,67,65,66,71,62,265000
Q3:75%,161.5,75.7,73,72,83.5,66.255,300000
99%,212.86,87,91.129,83.86,97,76.1142,NaN
Q4:100%,215,89.4,91.15,88.5,98,77.89,390000
IQR,107,15.1,12.1,11,23.5,8.31,60000
1.5rule,160.5,22.65,18.15,16.5,35.25,12.465,90000
lesser_per,-106,37.95,42.75,44.5,24.75,45.48,150000
greater_per,322,98.35,91.15,88.5,118.75,78.72,390000
Mini,1,40.89,42.75,50,50,51.21,200000
Max,215,89.4,91.15,88.5,98,77.89,390000
skew,0,-0.132649,0.162611,0.204164,0.282308,0.313576,0.8067
kurtosis,-1.2,-0.60751,0.0869008,-0.0974897,-1.08858,-0.470723,-0.239837