In [1]:
import pandas as pd

In [2]:
dataset=pd.read_csv("PrePlacement.csv")

In [3]:
dataset

,sl_no,ssc_p,hsc_p,degree_p,etest_p,mba_p,salary,gender,ssc_b,hsc_b,hsc_s,degree_t,workex,specialisation,status
0,1.0,67.00,91.00,58.00,55.0,58.80,270000.000000,M,Others,Others,Commerce,Sci&Tech,No,Mkt&HR,Placed
1,2.0,79.33,78.33,77.48,86.5,66.28,200000.000000,M,Central,Others,Science,Sci&Tech,Yes,Mkt&Fin,Placed
2,3.0,65.00,68.00,64.00,75.0,57.80,250000.000000,M,Central,Central,Arts,Comm&Mgmt,No,Mkt&Fin,Placed
3,4.0,56.00,52.00,52.00,66.0,59.43,288655.405405,M,Central,Central,Science,Sci&Tech,No,Mkt&HR,Not Placed
4,5.0,85.80,73.60,73.30,96.8,55.50,425000.000000,M,Central,Central,Commerce,Comm&Mgmt,No,Mkt&Fin,Placed
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
210,211.0,80.60,82.00,77.60,91.0,74.49,400000.000000,M,Others,Others,Commerce,Comm&Mgmt,No,Mkt&Fin,Placed
211,212.0,58.00,60.00,72.00,74.0,53.62,275000.000000,M,Others,Others,Science,Sci&Tech,No,Mkt&Fin,Placed
212,213.0,67.00,67.00,73.00,59.0,69.72,295000.000000,M,Others,Others,Commerce,Comm&Mgmt,Yes,Mkt&Fin,Placed
213,214.0,74.00,66.00,58.00,70.0,60.23,204000.000000,F,Others,Others,Commerce,Comm&Mgmt,No,Mkt&HR,Placed
214,215.0,62.00,58.00,53.00,89.0,60.22,288655.405405,M,Central,Others,Science,Comm&Mgmt,No,Mkt&HR,Not Placed

In [4]:
dataset.isna().sum()

sl_no             0
ssc_p             0
hsc_p             0
degree_p          0
etest_p           0
mba_p             0
salary            0
gender            0
ssc_b             0
hsc_b             0
hsc_s             0
degree_t          0
workex            0
specialisation    0
status            0
dtype: int64

In [5]:
from Univariate import Univariate

In [6]:
quan,qual=Univariate.quan_qual(dataset)

In [7]:
quan

['sl_no', 'ssc_p', 'hsc_p', 'degree_p', 'etest_p', 'mba_p', 'salary']

In [8]:
qual

['gender',
 'ssc_b',
 'hsc_b',
 'hsc_s',
 'degree_t',
 'workex',
 'specialisation',
 'status']

In [9]:
from Univariate import Univariate
import pandas as pd
descriptive= Univariate.descriptive_Tab(dataset,quan)

In [10]:
descriptive

              sl_no    ssc_p    hsc_p degree_p  etest_p    mba_p   salary
Mean            108  67.3034  66.3332  66.3702  72.1006  62.2782   288655
Median          108       67       65       66       71       62   288655
Mode              1       62       63       65       60     56.7   288655
Q1:25%         54.5     60.6     60.9       61       60   57.945   250000
Q2:50%          108       67       65       66       71       62   288655
Q3:75%        161.5     75.7       73       72     83.5   66.255   288655
99%          212.86       87    91.86    83.86       97  76.1142   629000
Q4:100%         215     89.4     97.7       91       98    77.89   940000
IQR             107     15.1     12.1       11     23.5     8.31  38655.4
1.5rule       160.5    22.65    18.15     16.5    35.25   12.465  57983.1
lesser_per     -106    37.95    42.75     44.5    24.75    45.48   192017
greater_per     322    98.35    91.15     88.5   118.75    78.72   346639
Mini              1    40.89       37       50       50    51.21   200000
Max             215     89.4     97.7       91       98    77.89   940000

In [11]:
lesser_de,greater_de=Univariate.detect_lesser_greater(quan,descriptive)

In [12]:
lesser_de

['hsc_p']

In [13]:
greater_de

['hsc_p', 'degree_p', 'salary']

#so we have to replace outliers.

In [14]:
def Replace_outliers(dataset,lesser_de,greater_de,descriptive):
    for column_names in lesser_de:
        dataset[column_names][dataset[column_names]<descriptive[column_names]["lesser_per"]]=descriptive[column_names]["lesser_per"]
    for column_names in greater_de:
        dataset[column_names][dataset[column_names]>descriptive[column_names]["greater_per"]]=descriptive[column_names]["greater_per"]
    return descriptive

In [15]:
Replace_outliers(dataset,lesser_de,greater_de,descriptive)

C:\Anaconda3\envs\aiml\lib\site-packages\ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  This is separate from the ipykernel package so we can avoid doing imports until
C:\Anaconda3\envs\aiml\lib\site-packages\ipykernel_launcher.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """

              sl_no    ssc_p    hsc_p degree_p  etest_p    mba_p   salary
Mean            108  67.3034  66.3332  66.3702  72.1006  62.2782   288655
Median          108       67       65       66       71       62   288655
Mode              1       62       63       65       60     56.7   288655
Q1:25%         54.5     60.6     60.9       61       60   57.945   250000
Q2:50%          108       67       65       66       71       62   288655
Q3:75%        161.5     75.7       73       72     83.5   66.255   288655
99%          212.86       87    91.86    83.86       97  76.1142   629000
Q4:100%         215     89.4     97.7       91       98    77.89   940000
IQR             107     15.1     12.1       11     23.5     8.31  38655.4
1.5rule       160.5    22.65    18.15     16.5    35.25   12.465  57983.1
lesser_per     -106    37.95    42.75     44.5    24.75    45.48   192017
greater_per     322    98.35    91.15     88.5   118.75    78.72   346639
Mini              1    40.89       37       50       50    51.21   200000
Max             215     89.4     97.7       91       98    77.89   940000

In [16]:
from Univariate import Univariate
import pandas as pd
Univariate.Replace_outliers(dataset,lesser_de,greater_de,descriptive)

D:\Week-6_Datascience_Bivariate\Univariate.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dataset[column_names][dataset[column_names]<descriptive[column_names]["lesser_per"]]=descriptive[column_names]
D:\Week-6_Datascience_Bivariate\Univariate.py:64: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dataset[column_names][dataset[column_names]>descriptive[column_names]["greater_per"]]=descriptive[column_names]

              sl_no    ssc_p    hsc_p degree_p  etest_p    mba_p   salary
Mean            108  67.3034  66.3332  66.3702  72.1006  62.2782   288655
Median          108       67       65       66       71       62   288655
Mode              1       62       63       65       60     56.7   288655
Q1:25%         54.5     60.6     60.9       61       60   57.945   250000
Q2:50%          108       67       65       66       71       62   288655
Q3:75%        161.5     75.7       73       72     83.5   66.255   288655
99%          212.86       87    91.86    83.86       97  76.1142   629000
Q4:100%         215     89.4     97.7       91       98    77.89   940000
IQR             107     15.1     12.1       11     23.5     8.31  38655.4
1.5rule       160.5    22.65    18.15     16.5    35.25   12.465  57983.1
lesser_per     -106    37.95    42.75     44.5    24.75    45.48   192017
greater_per     322    98.35    91.15     88.5   118.75    78.72   346639
Mini              1    40.89       37       50       50    51.21   200000
Max             215     89.4     97.7       91       98    77.89   940000

In [17]:
Preprocessed_disc

NameError: name 'Preprocessed_disc' is not defined

In [ ]:
lesser_de,greater_de=Univariate.detect_lesser_greater(quan,Preprocessed_disc)

In [ ]:
lesser_de

In [ ]:
greater_de