In [1]:
import pandas as pd

In [2]:
dataset=pd.read_csv("Placement.csv")

In [38]:
dataset

,sl_no,gender,ssc_p,ssc_b,hsc_p,hsc_b,hsc_s,degree_p,degree_t,workex,etest_p,specialisation,mba_p,status,salary
0,1,M,67.00,Others,91.00,Others,Commerce,58.00,Sci&Tech,No,55.0,Mkt&HR,58.80,Placed,270000.000000
1,2,M,79.33,Central,78.33,Others,Science,77.48,Sci&Tech,Yes,86.5,Mkt&Fin,66.28,Placed,200000.000000
2,3,M,65.00,Central,68.00,Central,Arts,64.00,Comm&Mgmt,No,75.0,Mkt&Fin,57.80,Placed,250000.000000
3,4,M,56.00,Central,52.00,Central,Science,52.00,Sci&Tech,No,66.0,Mkt&HR,59.43,Not Placed,288655.405405
4,5,M,85.80,Central,73.60,Central,Commerce,73.30,Comm&Mgmt,No,96.8,Mkt&Fin,55.50,Placed,425000.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
210,211,M,80.60,Others,82.00,Others,Commerce,77.60,Comm&Mgmt,No,91.0,Mkt&Fin,74.49,Placed,400000.000000
211,212,M,58.00,Others,60.00,Others,Science,72.00,Sci&Tech,No,74.0,Mkt&Fin,53.62,Placed,275000.000000
212,213,M,67.00,Others,67.00,Others,Commerce,73.00,Comm&Mgmt,Yes,59.0,Mkt&Fin,69.72,Placed,295000.000000
213,214,F,74.00,Others,66.00,Others,Commerce,58.00,Comm&Mgmt,No,70.0,Mkt&HR,60.23,Placed,204000.000000
214,215,M,62.00,Central,58.00,Others,Science,53.00,Comm&Mgmt,No,89.0,Mkt&HR,60.22,Not Placed,288655.405405

In [4]:
#salary column In dataset got NaN values we should clean it 
#lets check how many null values are there in this dataset?

In [5]:
dataset.isnull().sum()

sl_no              0
gender             0
ssc_p              0
ssc_b              0
hsc_p              0
hsc_b              0
hsc_s              0
degree_p           0
degree_t           0
workex             0
etest_p            0
specialisation     0
mba_p              0
status             0
salary            67
dtype: int64

In [6]:
dataset.isna().sum()

sl_no              0
gender             0
ssc_p              0
ssc_b              0
hsc_p              0
hsc_b              0
hsc_s              0
degree_p           0
degree_t           0
workex             0
etest_p            0
specialisation     0
mba_p              0
status             0
salary            67
dtype: int64

#methods to replace nan values 
#Method 1: Replace it by MCT(mean,median)
#Method 2: delete entire row 
#Method 3: Replace according to dataset.
#Method 4: consider this dataset as a semi-suppervised and find model to predict missing values.

#so we know salary column have 67 null values before procede we should clean it 
#first understand the position of this nan values. Nan values present when the student not get placed.

In [7]:
#Method 1: Replace it by MCT(mean,median) (Note: according to our dataset its just for practice)
dataset["salary"].fillna(dataset["salary"].mean(),inplace=True)

In [8]:
dataset #(Our Nan values filled by mean of salary)

,sl_no,gender,ssc_p,ssc_b,hsc_p,hsc_b,hsc_s,degree_p,degree_t,workex,etest_p,specialisation,mba_p,status,salary
0,1,M,67.00,Others,91.00,Others,Commerce,58.00,Sci&Tech,No,55.0,Mkt&HR,58.80,Placed,270000.000000
1,2,M,79.33,Central,78.33,Others,Science,77.48,Sci&Tech,Yes,86.5,Mkt&Fin,66.28,Placed,200000.000000
2,3,M,65.00,Central,68.00,Central,Arts,64.00,Comm&Mgmt,No,75.0,Mkt&Fin,57.80,Placed,250000.000000
3,4,M,56.00,Central,52.00,Central,Science,52.00,Sci&Tech,No,66.0,Mkt&HR,59.43,Not Placed,288655.405405
4,5,M,85.80,Central,73.60,Central,Commerce,73.30,Comm&Mgmt,No,96.8,Mkt&Fin,55.50,Placed,425000.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
210,211,M,80.60,Others,82.00,Others,Commerce,77.60,Comm&Mgmt,No,91.0,Mkt&Fin,74.49,Placed,400000.000000
211,212,M,58.00,Others,60.00,Others,Science,72.00,Sci&Tech,No,74.0,Mkt&Fin,53.62,Placed,275000.000000
212,213,M,67.00,Others,67.00,Others,Commerce,73.00,Comm&Mgmt,Yes,59.0,Mkt&Fin,69.72,Placed,295000.000000
213,214,F,74.00,Others,66.00,Others,Commerce,58.00,Comm&Mgmt,No,70.0,Mkt&HR,60.23,Placed,204000.000000
214,215,M,62.00,Central,58.00,Others,Science,53.00,Comm&Mgmt,No,89.0,Mkt&HR,60.22,Not Placed,288655.405405

In [9]:
#Method 2: delete entire row (Note: according to our dataset its just for practice)
dataset.dropna()

,sl_no,gender,ssc_p,ssc_b,hsc_p,hsc_b,hsc_s,degree_p,degree_t,workex,etest_p,specialisation,mba_p,status,salary
0,1,M,67.00,Others,91.00,Others,Commerce,58.00,Sci&Tech,No,55.0,Mkt&HR,58.80,Placed,270000.000000
1,2,M,79.33,Central,78.33,Others,Science,77.48,Sci&Tech,Yes,86.5,Mkt&Fin,66.28,Placed,200000.000000
2,3,M,65.00,Central,68.00,Central,Arts,64.00,Comm&Mgmt,No,75.0,Mkt&Fin,57.80,Placed,250000.000000
3,4,M,56.00,Central,52.00,Central,Science,52.00,Sci&Tech,No,66.0,Mkt&HR,59.43,Not Placed,288655.405405
4,5,M,85.80,Central,73.60,Central,Commerce,73.30,Comm&Mgmt,No,96.8,Mkt&Fin,55.50,Placed,425000.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
210,211,M,80.60,Others,82.00,Others,Commerce,77.60,Comm&Mgmt,No,91.0,Mkt&Fin,74.49,Placed,400000.000000
211,212,M,58.00,Others,60.00,Others,Science,72.00,Sci&Tech,No,74.0,Mkt&Fin,53.62,Placed,275000.000000
212,213,M,67.00,Others,67.00,Others,Commerce,73.00,Comm&Mgmt,Yes,59.0,Mkt&Fin,69.72,Placed,295000.000000
213,214,F,74.00,Others,66.00,Others,Commerce,58.00,Comm&Mgmt,No,70.0,Mkt&HR,60.23,Placed,204000.000000
214,215,M,62.00,Central,58.00,Others,Science,53.00,Comm&Mgmt,No,89.0,Mkt&HR,60.22,Not Placed,288655.405405

In [10]:
#Now we can see our row droped from 215 to 148.

In [11]:
#Method 3: Replace according to dataset.(This method is suitable for this dataset)
dataset["salary"].fillna(0,inplace=True)

In [12]:
dataset #(here we can see Nan value changed as 0)
#why this method is effective because its a numerical collumn so we replace with 0 without changing dataset)

,sl_no,gender,ssc_p,ssc_b,hsc_p,hsc_b,hsc_s,degree_p,degree_t,workex,etest_p,specialisation,mba_p,status,salary
0,1,M,67.00,Others,91.00,Others,Commerce,58.00,Sci&Tech,No,55.0,Mkt&HR,58.80,Placed,270000.000000
1,2,M,79.33,Central,78.33,Others,Science,77.48,Sci&Tech,Yes,86.5,Mkt&Fin,66.28,Placed,200000.000000
2,3,M,65.00,Central,68.00,Central,Arts,64.00,Comm&Mgmt,No,75.0,Mkt&Fin,57.80,Placed,250000.000000
3,4,M,56.00,Central,52.00,Central,Science,52.00,Sci&Tech,No,66.0,Mkt&HR,59.43,Not Placed,288655.405405
4,5,M,85.80,Central,73.60,Central,Commerce,73.30,Comm&Mgmt,No,96.8,Mkt&Fin,55.50,Placed,425000.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
210,211,M,80.60,Others,82.00,Others,Commerce,77.60,Comm&Mgmt,No,91.0,Mkt&Fin,74.49,Placed,400000.000000
211,212,M,58.00,Others,60.00,Others,Science,72.00,Sci&Tech,No,74.0,Mkt&Fin,53.62,Placed,275000.000000
212,213,M,67.00,Others,67.00,Others,Commerce,73.00,Comm&Mgmt,Yes,59.0,Mkt&Fin,69.72,Placed,295000.000000
213,214,F,74.00,Others,66.00,Others,Commerce,58.00,Comm&Mgmt,No,70.0,Mkt&HR,60.23,Placed,204000.000000
214,215,M,62.00,Central,58.00,Others,Science,53.00,Comm&Mgmt,No,89.0,Mkt&HR,60.22,Not Placed,288655.405405

In [13]:
#Method 4: consider this dataset as a semi-suppervised and find model to predict missing values.very rare method.

The above methods are suitable for one column 
what if Nan values present in more than 2 columns.

In [14]:
def quan_qual(dataset):
    quan=[]
    qual=[]
    for column_names in dataset.columns:
        if dataset[column_names].dtypes=="object":
            qual.append(column_names)
            
        else:
            quan.append(column_names)
            
    return quan,qual

In [15]:
quan,qual=quan_qual(dataset)

In [16]:
quan

['sl_no', 'ssc_p', 'hsc_p', 'degree_p', 'etest_p', 'mba_p', 'salary']

In [17]:
dataset.isna().sum()

sl_no             0
gender            0
ssc_p             0
ssc_b             0
hsc_p             0
hsc_b             0
hsc_s             0
degree_p          0
degree_t          0
workex            0
etest_p           0
specialisation    0
mba_p             0
status            0
salary            0
dtype: int64

In [18]:
#To sove the above challenge we have build in function.
import numpy as np
from sklearn.impute import SimpleImputer
imp = SimpleImputer(missing_values=np.nan, strategy='mean')
sim_imp=imp.fit_transform(dataset[quan])           #since this file can't process categorical data we pass quan
#imp.transform(dataset[quan])

In [19]:
sim_imp

array([[1.00000000e+00, 6.70000000e+01, 9.10000000e+01, ...,
        5.50000000e+01, 5.88000000e+01, 2.70000000e+05],
       [2.00000000e+00, 7.93300000e+01, 7.83300000e+01, ...,
        8.65000000e+01, 6.62800000e+01, 2.00000000e+05],
       [3.00000000e+00, 6.50000000e+01, 6.80000000e+01, ...,
        7.50000000e+01, 5.78000000e+01, 2.50000000e+05],
       ...,
       [2.13000000e+02, 6.70000000e+01, 6.70000000e+01, ...,
        5.90000000e+01, 6.97200000e+01, 2.95000000e+05],
       [2.14000000e+02, 7.40000000e+01, 6.60000000e+01, ...,
        7.00000000e+01, 6.02300000e+01, 2.04000000e+05],
       [2.15000000e+02, 6.20000000e+01, 5.80000000e+01, ...,
        8.90000000e+01, 6.02200000e+01, 2.88655405e+05]])

In [20]:
#dataset_Tab=pd.DataFrame(index=dataset[quan].index,columns=dataset[quan].columns) 
#if we run above code it gives dataframe with nan values)
dataset_Tab=pd.DataFrame(columns=dataset[quan].columns) #(this line of code gives only column names)

In [21]:
dataset_Tab

Empty DataFrame
Columns: [sl_no, ssc_p, hsc_p, degree_p, etest_p, mba_p, salary]
Index: []

In [22]:
dataset_Tab=pd.DataFrame(sim_imp,
    columns=dataset[quan].columns,
    index=dataset[quan].index) #(If we run this code we got below table)
#dataset_Tab=pd.DataFrame(sim_imp,columns=dataset[quan].columns) #(Same output from this code too)

In [23]:
dataset_Tab

     sl_no  ssc_p  hsc_p  degree_p  etest_p  mba_p         salary
0      1.0  67.00  91.00     58.00     55.0  58.80  270000.000000
1      2.0  79.33  78.33     77.48     86.5  66.28  200000.000000
2      3.0  65.00  68.00     64.00     75.0  57.80  250000.000000
3      4.0  56.00  52.00     52.00     66.0  59.43  288655.405405
4      5.0  85.80  73.60     73.30     96.8  55.50  425000.000000
..     ...    ...    ...       ...      ...    ...            ...
210  211.0  80.60  82.00     77.60     91.0  74.49  400000.000000
211  212.0  58.00  60.00     72.00     74.0  53.62  275000.000000
212  213.0  67.00  67.00     73.00     59.0  69.72  295000.000000
213  214.0  74.00  66.00     58.00     70.0  60.23  204000.000000
214  215.0  62.00  58.00     53.00     89.0  60.22  288655.405405

[215 rows x 7 columns]

#Here dataset_Tab is for only quantitative columns If you want preprocessed dataset you should merge 
#preprocessed quan and qual columns as single dataframe

#we have quan column we need to assing a variable for qual

In [24]:
df2=dataset[qual]

In [25]:
df2

,gender,ssc_b,hsc_b,hsc_s,degree_t,workex,specialisation,status
0,M,Others,Others,Commerce,Sci&Tech,No,Mkt&HR,Placed
1,M,Central,Others,Science,Sci&Tech,Yes,Mkt&Fin,Placed
2,M,Central,Central,Arts,Comm&Mgmt,No,Mkt&Fin,Placed
3,M,Central,Central,Science,Sci&Tech,No,Mkt&HR,Not Placed
4,M,Central,Central,Commerce,Comm&Mgmt,No,Mkt&Fin,Placed
...,...,...,...,...,...,...,...,...
210,M,Others,Others,Commerce,Comm&Mgmt,No,Mkt&Fin,Placed
211,M,Others,Others,Science,Sci&Tech,No,Mkt&Fin,Placed
212,M,Others,Others,Commerce,Comm&Mgmt,Yes,Mkt&Fin,Placed
213,F,Others,Others,Commerce,Comm&Mgmt,No,Mkt&HR,Placed
214,M,Central,Others,Science,Comm&Mgmt,No,Mkt&HR,Not Placed

In [26]:
merge=[dataset_Tab,df2] #To merge correctly position is very important

In [27]:
#preprocessed=pd.concat([dataset_Tab,df2]) #(we have merged dataframe but is in row wise merge we want to merge column wise
preprocessed=pd.concat(merge)
#for that we have to add this (axis=1) )

C:\Anaconda3\envs\aiml\lib\site-packages\ipykernel_launcher.py:2: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

In [28]:
preprocessed

,degree_p,degree_t,etest_p,gender,hsc_b,hsc_p,hsc_s,mba_p,salary,sl_no,specialisation,ssc_b,ssc_p,status,workex
0,58.00,NaN,55.0,NaN,NaN,91.00,NaN,58.80,270000.000000,1.0,NaN,NaN,67.00,NaN,NaN
1,77.48,NaN,86.5,NaN,NaN,78.33,NaN,66.28,200000.000000,2.0,NaN,NaN,79.33,NaN,NaN
2,64.00,NaN,75.0,NaN,NaN,68.00,NaN,57.80,250000.000000,3.0,NaN,NaN,65.00,NaN,NaN
3,52.00,NaN,66.0,NaN,NaN,52.00,NaN,59.43,288655.405405,4.0,NaN,NaN,56.00,NaN,NaN
4,73.30,NaN,96.8,NaN,NaN,73.60,NaN,55.50,425000.000000,5.0,NaN,NaN,85.80,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
210,NaN,Comm&Mgmt,NaN,M,Others,NaN,Commerce,NaN,NaN,NaN,Mkt&Fin,Others,NaN,Placed,No
211,NaN,Sci&Tech,NaN,M,Others,NaN,Science,NaN,NaN,NaN,Mkt&Fin,Others,NaN,Placed,No
212,NaN,Comm&Mgmt,NaN,M,Others,NaN,Commerce,NaN,NaN,NaN,Mkt&Fin,Others,NaN,Placed,Yes
213,NaN,Comm&Mgmt,NaN,F,Others,NaN,Commerce,NaN,NaN,NaN,Mkt&HR,Others,NaN,Placed,No
214,NaN,Comm&Mgmt,NaN,M,Others,NaN,Science,NaN,NaN,NaN,Mkt&HR,Central,NaN,Not Placed,No

In [29]:
preprocessed

,degree_p,degree_t,etest_p,gender,hsc_b,hsc_p,hsc_s,mba_p,salary,sl_no,specialisation,ssc_b,ssc_p,status,workex
0,58.00,NaN,55.0,NaN,NaN,91.00,NaN,58.80,270000.000000,1.0,NaN,NaN,67.00,NaN,NaN
1,77.48,NaN,86.5,NaN,NaN,78.33,NaN,66.28,200000.000000,2.0,NaN,NaN,79.33,NaN,NaN
2,64.00,NaN,75.0,NaN,NaN,68.00,NaN,57.80,250000.000000,3.0,NaN,NaN,65.00,NaN,NaN
3,52.00,NaN,66.0,NaN,NaN,52.00,NaN,59.43,288655.405405,4.0,NaN,NaN,56.00,NaN,NaN
4,73.30,NaN,96.8,NaN,NaN,73.60,NaN,55.50,425000.000000,5.0,NaN,NaN,85.80,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
210,NaN,Comm&Mgmt,NaN,M,Others,NaN,Commerce,NaN,NaN,NaN,Mkt&Fin,Others,NaN,Placed,No
211,NaN,Sci&Tech,NaN,M,Others,NaN,Science,NaN,NaN,NaN,Mkt&Fin,Others,NaN,Placed,No
212,NaN,Comm&Mgmt,NaN,M,Others,NaN,Commerce,NaN,NaN,NaN,Mkt&Fin,Others,NaN,Placed,Yes
213,NaN,Comm&Mgmt,NaN,F,Others,NaN,Commerce,NaN,NaN,NaN,Mkt&HR,Others,NaN,Placed,No
214,NaN,Comm&Mgmt,NaN,M,Others,NaN,Science,NaN,NaN,NaN,Mkt&HR,Central,NaN,Not Placed,No

In [30]:
preprocessed.isnull().sum()

degree_p          215
degree_t          215
etest_p           215
gender            215
hsc_b             215
hsc_p             215
hsc_s             215
mba_p             215
salary            215
sl_no             215
specialisation    215
ssc_b             215
ssc_p             215
status            215
workex            215
dtype: int64

In [31]:
#preprocessed=pd.concat((dataset_Tab,df2),axis=1) this method also gives same output
preprocessed=pd.concat((merge),axis=1)

In [32]:
preprocessed

,sl_no,ssc_p,hsc_p,degree_p,etest_p,mba_p,salary,gender,ssc_b,hsc_b,hsc_s,degree_t,workex,specialisation,status
0,1.0,67.00,91.00,58.00,55.0,58.80,270000.000000,M,Others,Others,Commerce,Sci&Tech,No,Mkt&HR,Placed
1,2.0,79.33,78.33,77.48,86.5,66.28,200000.000000,M,Central,Others,Science,Sci&Tech,Yes,Mkt&Fin,Placed
2,3.0,65.00,68.00,64.00,75.0,57.80,250000.000000,M,Central,Central,Arts,Comm&Mgmt,No,Mkt&Fin,Placed
3,4.0,56.00,52.00,52.00,66.0,59.43,288655.405405,M,Central,Central,Science,Sci&Tech,No,Mkt&HR,Not Placed
4,5.0,85.80,73.60,73.30,96.8,55.50,425000.000000,M,Central,Central,Commerce,Comm&Mgmt,No,Mkt&Fin,Placed
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
210,211.0,80.60,82.00,77.60,91.0,74.49,400000.000000,M,Others,Others,Commerce,Comm&Mgmt,No,Mkt&Fin,Placed
211,212.0,58.00,60.00,72.00,74.0,53.62,275000.000000,M,Others,Others,Science,Sci&Tech,No,Mkt&Fin,Placed
212,213.0,67.00,67.00,73.00,59.0,69.72,295000.000000,M,Others,Others,Commerce,Comm&Mgmt,Yes,Mkt&Fin,Placed
213,214.0,74.00,66.00,58.00,70.0,60.23,204000.000000,F,Others,Others,Commerce,Comm&Mgmt,No,Mkt&HR,Placed
214,215.0,62.00,58.00,53.00,89.0,60.22,288655.405405,M,Central,Others,Science,Comm&Mgmt,No,Mkt&HR,Not Placed

In [33]:
preprocessed.isnull().sum()

sl_no             0
ssc_p             0
hsc_p             0
degree_p          0
etest_p           0
mba_p             0
salary            0
gender            0
ssc_b             0
hsc_b             0
hsc_s             0
degree_t          0
workex            0
specialisation    0
status            0
dtype: int64

In [34]:
#good now convert this file into .csv file to use as dataset
preprocessed.to_csv("PrePlacement.csv",index=False) #(dataset.to_csv(key word)("file name") 
#index=False,its omits duplicate index)

In [35]:
preprocessed #(this dataset not look like our default dataset because of hard readability.)
#so we have to re-arrange the columns positions

,sl_no,ssc_p,hsc_p,degree_p,etest_p,mba_p,salary,gender,ssc_b,hsc_b,hsc_s,degree_t,workex,specialisation,status
0,1.0,67.00,91.00,58.00,55.0,58.80,270000.000000,M,Others,Others,Commerce,Sci&Tech,No,Mkt&HR,Placed
1,2.0,79.33,78.33,77.48,86.5,66.28,200000.000000,M,Central,Others,Science,Sci&Tech,Yes,Mkt&Fin,Placed
2,3.0,65.00,68.00,64.00,75.0,57.80,250000.000000,M,Central,Central,Arts,Comm&Mgmt,No,Mkt&Fin,Placed
3,4.0,56.00,52.00,52.00,66.0,59.43,288655.405405,M,Central,Central,Science,Sci&Tech,No,Mkt&HR,Not Placed
4,5.0,85.80,73.60,73.30,96.8,55.50,425000.000000,M,Central,Central,Commerce,Comm&Mgmt,No,Mkt&Fin,Placed
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
210,211.0,80.60,82.00,77.60,91.0,74.49,400000.000000,M,Others,Others,Commerce,Comm&Mgmt,No,Mkt&Fin,Placed
211,212.0,58.00,60.00,72.00,74.0,53.62,275000.000000,M,Others,Others,Science,Sci&Tech,No,Mkt&Fin,Placed
212,213.0,67.00,67.00,73.00,59.0,69.72,295000.000000,M,Others,Others,Commerce,Comm&Mgmt,Yes,Mkt&Fin,Placed
213,214.0,74.00,66.00,58.00,70.0,60.23,204000.000000,F,Others,Others,Commerce,Comm&Mgmt,No,Mkt&HR,Placed
214,215.0,62.00,58.00,53.00,89.0,60.22,288655.405405,M,Central,Others,Science,Comm&Mgmt,No,Mkt&HR,Not Placed

In [37]:
preprocessed.columns

Index(['sl_no', 'ssc_p', 'hsc_p', 'degree_p', 'etest_p', 'mba_p', 'salary',
       'gender', 'ssc_b', 'hsc_b', 'hsc_s', 'degree_t', 'workex',
       'specialisation', 'status'],
      dtype='object')

In [39]:
#expri_dataset=pd.DataFrame(columns=dataset.columns)
expri_dataset=dataset

In [40]:
expri_dataset

,sl_no,gender,ssc_p,ssc_b,hsc_p,hsc_b,hsc_s,degree_p,degree_t,workex,etest_p,specialisation,mba_p,status,salary
0,1,M,67.00,Others,91.00,Others,Commerce,58.00,Sci&Tech,No,55.0,Mkt&HR,58.80,Placed,270000.000000
1,2,M,79.33,Central,78.33,Others,Science,77.48,Sci&Tech,Yes,86.5,Mkt&Fin,66.28,Placed,200000.000000
2,3,M,65.00,Central,68.00,Central,Arts,64.00,Comm&Mgmt,No,75.0,Mkt&Fin,57.80,Placed,250000.000000
3,4,M,56.00,Central,52.00,Central,Science,52.00,Sci&Tech,No,66.0,Mkt&HR,59.43,Not Placed,288655.405405
4,5,M,85.80,Central,73.60,Central,Commerce,73.30,Comm&Mgmt,No,96.8,Mkt&Fin,55.50,Placed,425000.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
210,211,M,80.60,Others,82.00,Others,Commerce,77.60,Comm&Mgmt,No,91.0,Mkt&Fin,74.49,Placed,400000.000000
211,212,M,58.00,Others,60.00,Others,Science,72.00,Sci&Tech,No,74.0,Mkt&Fin,53.62,Placed,275000.000000
212,213,M,67.00,Others,67.00,Others,Commerce,73.00,Comm&Mgmt,Yes,59.0,Mkt&Fin,69.72,Placed,295000.000000
213,214,F,74.00,Others,66.00,Others,Commerce,58.00,Comm&Mgmt,No,70.0,Mkt&HR,60.23,Placed,204000.000000
214,215,M,62.00,Central,58.00,Others,Science,53.00,Comm&Mgmt,No,89.0,Mkt&HR,60.22,Not Placed,288655.405405

In [41]:
expri_dataset.isna().sum()

sl_no             0
gender            0
ssc_p             0
ssc_b             0
hsc_p             0
hsc_b             0
hsc_s             0
degree_p          0
degree_t          0
workex            0
etest_p           0
specialisation    0
mba_p             0
status            0
salary            0
dtype: int64